<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>hierarchy</name>
   <tag></tag>
   <elementGuidId>a6db2df0-20fd-4703-8941-476f264338e3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hierarchy</value>
      <webElementGuid>91b5fcbb-6e9e-49f9-83b6-2984ecefc17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a3ff540-fadd-4f2e-891b-803d1c7cebfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1422</value>
      <webElementGuid>0315916d-f8a0-4bc7-a727-88e1423beb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rotation</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b3b8225-b8c7-4d0a-ba60-e80715968f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>720</value>
      <webElementGuid>eb23dc7e-2336-433d-b1d9-ba7fd2e5e53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy</value>
      <webElementGuid>a1069e60-301a-4ca7-b532-fedf96f37cb8</webElementGuid>
   </webElementProperties>
   <locator>//hierarchy[count(. | //*[@class = 'hierarchy' and @index = '0' and @height = '1422' and @rotation = '0' and @width = '720']) = count(//*[@class = 'hierarchy' and @index = '0' and @height = '1422' and @rotation = '0' and @width = '720'])]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
