<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>PRUEBA</description>
   <name>01 HU - Login-Cierre de Sesión</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2b68d1c7-b495-4f48-b4b6-2644b10a0884</testSuiteGuid>
   <testCaseLink>
      <guid>b008282e-5c35-47d0-b3df-18ba2ed2d9f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/01 Especificaciones Funcionales - Primer Login exitoso del Cliente</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>abce727c-608e-470f-a9d1-43bdbc972980</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cf4846b-4b1a-4226-8d6b-e8239ff02515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>525617b1-5971-4fe1-be66-eac0e700569a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0d7f390-ad23-4e3a-b43e-d8b930786e13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cc2c0d7-86bd-45c9-bee6-5b81f469303a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79c5fe12-b97c-4f10-b8f7-421980f417d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b0c02f9-508e-430d-8c11-0b575b21b3fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/03Especificaciones funcionales - Botón Plano Olvidaste tu contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0c5b2541-0d06-428f-bc7c-d9522ba252b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/04 Estructura de la pantalla - Splash</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a6a7fe3d-d4fb-47f5-a311-5ab2321f82c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/05 Especificaciones Funcionales - Focus</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5ee04dae-0a75-4b66-abd3-c4954179b8a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/06 Especificaciones Funcionales - Número de Celular</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc17795-4239-44ac-8ece-a460ca9dd2d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>991d03e9-2c52-4750-9bae-e45db85b4df5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/07 Especificaciones Funcionales - Campo contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79af25b6-b766-4742-94f6-9f486f09a5f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3fddabf-ff18-4ce2-b9fb-b1eb86483923</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/08 Especificaciones Funcionales Numero de Celular -Contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4bc0c4dd-7c64-4128-aced-f92673f95c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/09 Especificaciones Funcionales - Validaciones del Campo Contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df237c05-b09a-4253-81e5-6095fa5f1fb2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>983d3610-91f2-4f52-a346-500c0b13d79f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/10 Especificaciones Funcionales para el campo numero de Celular</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad62ab01-fadc-4377-b2e6-53355a1eb933</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ed2fc84-0ed5-4aaa-8506-f81b9ff4894c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/11 Especificaciones Funcionales - Login exitoso del usuario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa40e843-545b-4268-94a5-a91d36206b7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7056b8e8-b170-4b35-a211-c04471a9c3a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0bd30d-506e-44ed-a342-394ca8b9506c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/12Especificaciones Funcionales - Login Fallido del usuario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57ac8371-751c-4911-bb17-201164881dfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f410f5e-2d40-43e0-8169-5ff0739905fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0e9d804-0213-4a0e-991c-7c87ce289564</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/13 Especificaciones funcionales - Cierre de Sesión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>986de76c-986b-421b-83a3-3ecdc0c594cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/14 Cierre de Sesion - Tiempo de Inactividad</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe72b9bd-5c26-4a8e-935b-b80cc506dbab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85724bda-865d-42ad-b537-99cf7b2757f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0ef7d48-dbb9-4c57-b822-66f8c70639ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/15 Cerrar sesión del cliente desde la pantalla Dashboard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d8cfed64-8bdf-4c3d-b6a6-501b534977d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/16 Cierre de sesión del cliente desde la pantalla Resumen de Saldo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>738c0a8c-c45e-468d-be9c-c122eafbaab2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/17 Cierre de Sesión - Desde la pantalla Resumen -por Tiempo de Inactividad</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fa86727a-0046-4987-b9e5-de8527c69337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/18 Validaciones Funcionales - Intentar iniciar sesión con falla de conexión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c437cf-ce72-47c4-9696-17d9fe1b55d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/19 Estructura de pantalla - Pantalla Cierre de sesión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>PRUEBA</description>
   <name>01 HU - Login-Cierre de Sesión</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2b68d1c7-b495-4f48-b4b6-2644b10a0884</testSuiteGuid>
   <testCaseLink>
      <guid>b008282e-5c35-47d0-b3df-18ba2ed2d9f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/02Estructura de la pantalla - Pantalla de Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2d72b0d-e6b7-4466-a995-1e903a3d0df4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2404252-aade-41f7-8aa1-ec65c27e8ec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f84db75-9519-47c1-abac-4f37cfdc31a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d92a8353-e5b8-4e5b-913b-8800d0958cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bc503f9-d2f9-4d65-8ef8-a56f43527431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9f7a5f0-287d-44df-a51d-cb2ce64f950f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f8a2dee-2d54-4151-8771-ea8092988a28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7b2f94-1881-4e66-be42-b0d4e8e65f8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d25b4150-19b4-4c7b-8bb1-22dec99f7719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cf998bb-5b81-4e2f-bcf5-490bcf7a43a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b0c02f9-508e-430d-8c11-0b575b21b3fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/03Especificaciones funcionales - Botón Plano Olvidaste tu contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c17cd66b-482c-4683-b8a1-e04a3498c5ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8342f07c-4fc5-4729-a67c-7d28f81ba520</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cb77ab9-e651-488e-a8b9-7a823912c3b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c25c4629-9a77-4347-abb1-a75a6822a626</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d9f0cb-4ee1-4bef-8f7e-6524a52aca0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1610d3eb-8d00-41c4-ba44-b8d5674203ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1da7883-ded0-402b-844c-544cb732358a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bb9dc96-897a-4b96-aec9-e92964e5718b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>404ba2ee-933f-4088-bc78-2e2b6ab271ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0c5b2541-0d06-428f-bc7c-d9522ba252b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/04 Estructura de la pantalla - Splash</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea3790ef-4fd9-4452-8e5a-94aaeed840e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6a7fe3d-d4fb-47f5-a311-5ab2321f82c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/05 Especificaciones Funcionales - Focus</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5ee04dae-0a75-4b66-abd3-c4954179b8a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/06 Especificaciones Funcionales - Validaciones del campo Número de Celular</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cc17795-4239-44ac-8ece-a460ca9dd2d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>991d03e9-2c52-4750-9bae-e45db85b4df5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/07 Especificaciones Funcionales - Campo contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79af25b6-b766-4742-94f6-9f486f09a5f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86198ec9-b8c9-4e36-94af-a51dffd09a8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3fddabf-ff18-4ce2-b9fb-b1eb86483923</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/08 Especificaciones Funcionales Numero de Celular -Contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52640321-d8b7-4c0b-93af-6f3ca596565a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>685ec57b-56d1-4f72-923e-8f3d67630b6e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bc0c4dd-7c64-4128-aced-f92673f95c3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/09 Especificaciones Funcionales - Validaciones del Campo Contraseña</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df237c05-b09a-4253-81e5-6095fa5f1fb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e73de688-3c40-4aec-92b1-bb8ba0e657f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>983d3610-91f2-4f52-a346-500c0b13d79f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/10 Especificaciones Funcionales para el campo numero de Celular</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad62ab01-fadc-4377-b2e6-53355a1eb933</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4fe543c-671d-4ad3-9326-38e9f6303532</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ed2fc84-0ed5-4aaa-8506-f81b9ff4894c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/11 Especificaciones Funcionales - Login exitoso del usuario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa40e843-545b-4268-94a5-a91d36206b7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7056b8e8-b170-4b35-a211-c04471a9c3a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bc0bd30d-506e-44ed-a342-394ca8b9506c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/12Especificaciones Funcionales - Login Fallido del usuario</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ff85a7d-6eff-4135-b259-a026e6b24917</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>640a2e76-02fb-4233-b63d-dfc0519919f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6259302-b02e-4fd2-955d-e47c8b05e7fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7903610-f309-4048-b860-84789d843787</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0e9d804-0213-4a0e-991c-7c87ce289564</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/13 Especificaciones funcionales - Cierre de Sesión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>986de76c-986b-421b-83a3-3ecdc0c594cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/14 Cierre de Sesion - Tiempo de Inactividad</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b0ef7d48-dbb9-4c57-b822-66f8c70639ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/15 Cerrar sesión del cliente desde la pantalla Dashboard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d8cfed64-8bdf-4c3d-b6a6-501b534977d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/16 Cierre de sesión del cliente desde la pantalla Resumen de Saldo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>738c0a8c-c45e-468d-be9c-c122eafbaab2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/17 Cierre de Sesión - Desde la pantalla Resumen -por Tiempo de Inactividad</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fa86727a-0046-4987-b9e5-de8527c69337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/18 Validaciones Funcionales - Intentar iniciar sesión con falla de conexión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e4c437cf-ce72-47c4-9696-17d9fe1b55d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01HU-Login-Cierre de Sesión/19 Estructura de pantalla - Pantalla Cierre de sesión</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
>>>>>>> branch 'main' of https://github.com/QASybven/UENO-App-Android
